### PR TITLE
Fetch efficiently

### PR DESCRIPTION
**Pull request by ghost**
By only cloning the 1st depth the download size is reduced by almost 200mb and more as Ishiiruka gets bigger.

### CODE REVIEW

**Comment by Ptomerty** [comment]
Forgive me for asking, but does depth=1 fetch enough history to clone this specific commit if Tino decides to update the repo? Because from what I'm reading, depth=1 only fetches the tips (the most recent commit), and there is no guarantee that the netplay-specific commit will be the most recent one, or even included in the 20 most recent ones (see 4.4).

I did find [this](https://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository/30701724#30701724) for efficiently cloning a single commit, but I do not know if github has server side support, although it should. Feel free to update your PR with the above!

**Comment by ghost** [comment]
Testing these commits right now on linux I think this should work. You are right I did not even consider the difference in commits from Ishiiruka to FM, my b.

**Comment by Ptomerty** [comment]
Thank you! I'll do a quick build + desync test then merge.

**Comment by Ptomerty** [comment]
Hmm. I tried with your version, and it *does* clone only d462ca387, but due to the specific commit it forces me to switch branch to "d462ca387", which leads to a different commit hash upon compilation, which is NOT d462ca387, and causes people to not be able to connect. Any way around this?

Note: once you've built, open up a netplay server. Your name should be `Player[1]: d462ca387 Lin`; this is the only combination that will prevent desyncs.

Sorry!

**Comment by ghost** [comment]
Thanks for testing! I didn't think that would be a problem. Going to try to find a work around tho!

**Comment by Ptomerty** [comment]
Unfortunately this won't work either: if you look at `v1.3~reg1` in the changelog, you'll see that I've tried this before. CMake requires the git history to produce a hash that doesn't desync with other computers.

**Comment by Ptomerty** [comment]
As it appears that the original PR submitter has deleted their account, I am closing this PR.

**Pull request closed without merging**
